### ISSUE TITLE
osem pulling JavaScript from localhost

### ISSUE THREAD

**Issue by lufthans** [SeaGL/osem#16]
It's easy to see with uMatrix as there's a line for localhost.

----
       
        <script type="text/javascript">
        var pkBaseURL = (("https:" == document.location.protocol) ? "https://localhost/" : "http://localhost/");
        document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
        </script><script type="text/javascript">
----

**Comment by lufthans** [comment]
Here's a screenshot of uMatrix showing the line for localhost

**Comment by vmbrasseur** [comment]
@lufthans …no screenshot attached?

**Comment by lufthans** [comment]
Had to allow another JS domain in order to upload

**Comment by differentreality** [comment]
That's probably because piwik hasn't been configured.
Not sure if you can easily pull the latest change from upstream with the current commits that have been added: 
https://github.com/openSUSE/osem/blob/master/config/piwik.yml.example#L15
Which could be:
`url: <%= ENV['OSEM_HOSTNAME'] %>`
supposing the variable is set in .env or .env.production file. Alternatively osem.seagl.org

**Comment by AndrewKvalheim** [comment]
I've just disabled Piwik/Matomo.

```yaml
# /srv/www/osem/shared/config/piwik.yml

default: &default
  disabled: yes

production:
  piwik:
    <<: *default

development:
  piwik:
    <<: *default

test:
  piwik:
    <<: *default
```
